In [1]:
import csv
import pandas as pd

In [2]:
merged_data = pd.read_csv('data/processed/merged_data.csv')

In [4]:
#norm_feature_list = ['UNITS', 'PRICE', 'BASE_PRICE']
norm_feature_list = ['STORE_NUM', 'UPC', 'UNITS', 'PRICE', 'BASE_PRICE', 'STORE_ID', 'MSA_CODE', 'SALES_AREA_SIZE_NUM', 'AVG_WEEKLY_BASKETS']

In [5]:
merged_data.columns.values.tolist()

['Unnamed: 0',
 'WEEK_END_DATE',
 'STORE_NUM',
 'UPC',
 'UNITS',
 'VISITS',
 'HHS',
 'SPEND',
 'PRICE',
 'BASE_PRICE',
 'FEATURE',
 'DISPLAY',
 'TPR_ONLY',
 'DESCRIPTION',
 'MANUFACTURER',
 'CATEGORY',
 'SUB_CATEGORY',
 'PRODUCT_SIZE',
 'STORE_ID',
 'STORE_NAME',
 'ADDRESS_CITY_NAME',
 'ADDRESS_STATE_PROV_CODE',
 'MSA_CODE',
 'SEG_VALUE_NAME',
 'PARKING_SPACE_QTY',
 'SALES_AREA_SIZE_NUM',
 'AVG_WEEKLY_BASKETS']

In [7]:
merged_feature_list = ['WEEK_END_DATE',
 'STORE_NUM',
 'UPC',
 'UNITS',
 'VISITS',
 'HHS',
 'SPEND',
 'PRICE',
 'BASE_PRICE',
 'FEATURE',
 'DISPLAY',
 'TPR_ONLY',
 'DESCRIPTION',
 'MANUFACTURER',
 'CATEGORY',
 'SUB_CATEGORY',
 'PRODUCT_SIZE',
 'STORE_ID',
 'STORE_NAME',
 'ADDRESS_CITY_NAME',
 'ADDRESS_STATE_PROV_CODE',
 'MSA_CODE',
 'SEG_VALUE_NAME',
 'SALES_AREA_SIZE_NUM',
 'AVG_WEEKLY_BASKETS']

In [8]:
merged_data = merged_data[merged_feature_list]

In [9]:
merged_data

,WEEK_END_DATE,STORE_NUM,UPC,UNITS,VISITS,HHS,SPEND,PRICE,BASE_PRICE,FEATURE,...,SUB_CATEGORY,PRODUCT_SIZE,STORE_ID,STORE_NAME,ADDRESS_CITY_NAME,ADDRESS_STATE_PROV_CODE,MSA_CODE,SEG_VALUE_NAME,SALES_AREA_SIZE_NUM,AVG_WEEKLY_BASKETS
0,2009-01-14,367,1111009477,13,13,13,18.07,1.39,1.57,0,...,PRETZELS,15 OZ,367,15TH & MADISON,COVINGTON,KY,17140,VALUE,24721,12706.532051
1,2009-01-14,367,1111009497,20,18,18,27.80,1.39,1.39,0,...,PRETZELS,15 OZ,367,15TH & MADISON,COVINGTON,KY,17140,VALUE,24721,12706.532051
2,2009-01-14,367,1111009507,14,14,14,19.32,1.38,1.38,0,...,PRETZELS,15 OZ,367,15TH & MADISON,COVINGTON,KY,17140,VALUE,24721,12706.532051
3,2009-01-14,367,1111035398,4,3,3,14.00,3.50,4.49,0,...,MOUTHWASHES (ANTISEPTIC),1.5 LT,367,15TH & MADISON,COVINGTON,KY,17140,VALUE,24721,12706.532051
4,2009-01-14,367,1111038078,3,3,3,7.50,2.50,2.50,0,...,MOUTHWASHES (ANTISEPTIC),500 ML,367,15TH & MADISON,COVINGTON,KY,17140,VALUE,24721,12706.532051
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
524945,2012-01-04,29159,31254742735,1,1,1,4.97,4.97,4.97,0,...,MOUTHWASHES (ANTISEPTIC),1 LT,29159,CARROLLTON,CARROLLTON,TX,19100,MAINSTREAM,54927,25916.532051
524946,2012-01-04,29159,31254742835,5,5,5,24.85,4.97,4.97,0,...,MOUTHWASHES (ANTISEPTIC),1 LT,29159,CARROLLTON,CARROLLTON,TX,19100,MAINSTREAM,54927,25916.532051
524947,2012-01-04,29159,88491201426,32,29,23,105.92,3.31,3.31,0,...,ADULT CEREAL,18 OZ,29159,CARROLLTON,CARROLLTON,TX,19100,MAINSTREAM,54927,25916.532051
524948,2012-01-04,29159,88491201427,30,26,23,99.30,3.31,3.31,0,...,ADULT CEREAL,18 OZ,29159,CARROLLTON,CARROLLTON,TX,19100,MAINSTREAM,54927,25916.532051
524949,2012-01-04,29159,88491212971,20,20,20,44.40,2.22,2.85,0,...,KIDS CEREAL,11 OZ,29159,CARROLLTON,CARROLLTON,TX,19100,MAINSTREAM,54927,25916.532051

In [10]:
merged_data[merged_data['STORE_NUM']==2277]

,WEEK_END_DATE,STORE_NUM,UPC,UNITS,VISITS,HHS,SPEND,PRICE,BASE_PRICE,FEATURE,...,SUB_CATEGORY,PRODUCT_SIZE,STORE_ID,STORE_NAME,ADDRESS_CITY_NAME,ADDRESS_STATE_PROV_CODE,MSA_CODE,SEG_VALUE_NAME,SALES_AREA_SIZE_NUM,AVG_WEEKLY_BASKETS
209,2009-01-14,2277,1111009477,158,140,135,218.04,1.38,1.24,0,...,PRETZELS,15 OZ,2277,ANDERSON TOWNE CTR,CINCINNATI,OH,17140,UPSCALE,81958,54052.519231
210,2009-01-14,2277,1111009497,179,161,157,247.02,1.38,1.24,0,...,PRETZELS,15 OZ,2277,ANDERSON TOWNE CTR,CINCINNATI,OH,17140,UPSCALE,81958,54052.519231
211,2009-01-14,2277,1111009507,35,34,34,48.30,1.38,1.38,0,...,PRETZELS,15 OZ,2277,ANDERSON TOWNE CTR,CINCINNATI,OH,17140,UPSCALE,81958,54052.519231
212,2009-01-14,2277,1111035398,9,8,8,31.14,3.46,4.49,0,...,MOUTHWASHES (ANTISEPTIC),1.5 LT,2277,ANDERSON TOWNE CTR,CINCINNATI,OH,17140,UPSCALE,81958,54052.519231
213,2009-01-14,2277,1111038078,12,12,12,31.08,2.59,4.51,0,...,MOUTHWASHES (ANTISEPTIC),500 ML,2277,ANDERSON TOWNE CTR,CINCINNATI,OH,17140,UPSCALE,81958,54052.519231
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
521885,2012-01-04,2277,31254742735,11,11,11,54.67,4.97,4.97,0,...,MOUTHWASHES (ANTISEPTIC),1 LT,2277,ANDERSON TOWNE CTR,CINCINNATI,OH,17140,UPSCALE,81958,54052.519231
521886,2012-01-04,2277,31254742835,15,14,14,74.55,4.97,4.97,0,...,MOUTHWASHES (ANTISEPTIC),1 LT,2277,ANDERSON TOWNE CTR,CINCINNATI,OH,17140,UPSCALE,81958,54052.519231
521887,2012-01-04,2277,88491201426,21,19,19,70.77,3.37,3.37,0,...,ADULT CEREAL,18 OZ,2277,ANDERSON TOWNE CTR,CINCINNATI,OH,17140,UPSCALE,81958,54052.519231
521888,2012-01-04,2277,88491201427,13,12,12,43.81,3.37,3.37,0,...,ADULT CEREAL,18 OZ,2277,ANDERSON TOWNE CTR,CINCINNATI,OH,17140,UPSCALE,81958,54052.519231
521889,2012-01-04,2277,88491212971,68,61,60,136.68,2.01,2.99,0,...,KIDS CEREAL,11 OZ,2277,ANDERSON TOWNE CTR,CINCINNATI,OH,17140,UPSCALE,81958,54052.519231

In [11]:
from sklearn import preprocessing

In [12]:
zscore = preprocessing.StandardScaler()

In [13]:
merged_data['PRICE'] = zscore.fit_transform(merged_data['PRICE'].values.reshape(-1,1))

In [14]:
merged_data['PRICE']

0        -1.277606
1        -1.277606
2        -1.284020
3         0.075563
4        -0.565749
            ...
524945    1.018293
524946    1.018293
524947   -0.046286
524948   -0.046286
524949   -0.745317
Name: PRICE, Length: 524950, dtype: float64

In [15]:
merged_data

,WEEK_END_DATE,STORE_NUM,UPC,UNITS,VISITS,HHS,SPEND,PRICE,BASE_PRICE,FEATURE,...,SUB_CATEGORY,PRODUCT_SIZE,STORE_ID,STORE_NAME,ADDRESS_CITY_NAME,ADDRESS_STATE_PROV_CODE,MSA_CODE,SEG_VALUE_NAME,SALES_AREA_SIZE_NUM,AVG_WEEKLY_BASKETS
0,2009-01-14,367,1111009477,13,13,13,18.07,-1.277606,1.57,0,...,PRETZELS,15 OZ,367,15TH & MADISON,COVINGTON,KY,17140,VALUE,24721,12706.532051
1,2009-01-14,367,1111009497,20,18,18,27.80,-1.277606,1.39,0,...,PRETZELS,15 OZ,367,15TH & MADISON,COVINGTON,KY,17140,VALUE,24721,12706.532051
2,2009-01-14,367,1111009507,14,14,14,19.32,-1.284020,1.38,0,...,PRETZELS,15 OZ,367,15TH & MADISON,COVINGTON,KY,17140,VALUE,24721,12706.532051
3,2009-01-14,367,1111035398,4,3,3,14.00,0.075563,4.49,0,...,MOUTHWASHES (ANTISEPTIC),1.5 LT,367,15TH & MADISON,COVINGTON,KY,17140,VALUE,24721,12706.532051
4,2009-01-14,367,1111038078,3,3,3,7.50,-0.565749,2.50,0,...,MOUTHWASHES (ANTISEPTIC),500 ML,367,15TH & MADISON,COVINGTON,KY,17140,VALUE,24721,12706.532051
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
524945,2012-01-04,29159,31254742735,1,1,1,4.97,1.018293,4.97,0,...,MOUTHWASHES (ANTISEPTIC),1 LT,29159,CARROLLTON,CARROLLTON,TX,19100,MAINSTREAM,54927,25916.532051
524946,2012-01-04,29159,31254742835,5,5,5,24.85,1.018293,4.97,0,...,MOUTHWASHES (ANTISEPTIC),1 LT,29159,CARROLLTON,CARROLLTON,TX,19100,MAINSTREAM,54927,25916.532051
524947,2012-01-04,29159,88491201426,32,29,23,105.92,-0.046286,3.31,0,...,ADULT CEREAL,18 OZ,29159,CARROLLTON,CARROLLTON,TX,19100,MAINSTREAM,54927,25916.532051
524948,2012-01-04,29159,88491201427,30,26,23,99.30,-0.046286,3.31,0,...,ADULT CEREAL,18 OZ,29159,CARROLLTON,CARROLLTON,TX,19100,MAINSTREAM,54927,25916.532051
524949,2012-01-04,29159,88491212971,20,20,20,44.40,-0.745317,2.85,0,...,KIDS CEREAL,11 OZ,29159,CARROLLTON,CARROLLTON,TX,19100,MAINSTREAM,54927,25916.532051

In [17]:
for feature in norm_feature_list:
    merged_data[feature] = zscore.fit_transform(merged_data[feature].values.reshape(-1,1))

In [18]:
merged_data

,WEEK_END_DATE,STORE_NUM,UPC,UNITS,VISITS,HHS,SPEND,PRICE,BASE_PRICE,FEATURE,...,SUB_CATEGORY,PRODUCT_SIZE,STORE_ID,STORE_NAME,ADDRESS_CITY_NAME,ADDRESS_STATE_PROV_CODE,MSA_CODE,SEG_VALUE_NAME,SALES_AREA_SIZE_NUM,AVG_WEEKLY_BASKETS
0,2009-01-14,-1.610890,-0.442202,-0.220760,13,13,18.07,-1.277606,-1.245766,0,...,PRETZELS,15 OZ,-1.610890,15TH & MADISON,COVINGTON,KY,-0.645367,VALUE,-1.887698,-1.350373
1,2009-01-14,-1.610890,-0.442202,0.013087,18,18,27.80,-1.277606,-1.356078,0,...,PRETZELS,15 OZ,-1.610890,15TH & MADISON,COVINGTON,KY,-0.645367,VALUE,-1.887698,-1.350373
2,2009-01-14,-1.610890,-0.442202,-0.187353,14,14,19.32,-1.284020,-1.362207,0,...,PRETZELS,15 OZ,-1.610890,15TH & MADISON,COVINGTON,KY,-0.645367,VALUE,-1.887698,-1.350373
3,2009-01-14,-1.610890,-0.442201,-0.521420,3,3,14.00,0.075563,0.543752,0,...,MOUTHWASHES (ANTISEPTIC),1.5 LT,-1.610890,15TH & MADISON,COVINGTON,KY,-0.645367,VALUE,-1.887698,-1.350373
4,2009-01-14,-1.610890,-0.442201,-0.554826,3,3,7.50,-0.565749,-0.675817,0,...,MOUTHWASHES (ANTISEPTIC),500 ML,-1.610890,15TH & MADISON,COVINGTON,KY,-0.645367,VALUE,-1.887698,-1.350373
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
524945,2012-01-04,1.627287,1.005835,-0.621640,1,1,4.97,1.018293,0.837919,0,...,MOUTHWASHES (ANTISEPTIC),1 LT,1.627287,CARROLLTON,CARROLLTON,TX,-0.329229,MAINSTREAM,0.360763,0.134685
524946,2012-01-04,1.627287,1.005835,-0.488013,5,5,24.85,1.018293,0.837919,0,...,MOUTHWASHES (ANTISEPTIC),1 LT,1.627287,CARROLLTON,CARROLLTON,TX,-0.329229,MAINSTREAM,0.360763,0.134685
524947,2012-01-04,1.627287,3.755346,0.413967,29,23,105.92,-0.046286,-0.179410,0,...,ADULT CEREAL,18 OZ,1.627287,CARROLLTON,CARROLLTON,TX,-0.329229,MAINSTREAM,0.360763,0.134685
524948,2012-01-04,1.627287,3.755346,0.347153,26,23,99.30,-0.046286,-0.179410,0,...,ADULT CEREAL,18 OZ,1.627287,CARROLLTON,CARROLLTON,TX,-0.329229,MAINSTREAM,0.360763,0.134685
524949,2012-01-04,1.627287,3.755346,0.013087,20,20,44.40,-0.745317,-0.461320,0,...,KIDS CEREAL,11 OZ,1.627287,CARROLLTON,CARROLLTON,TX,-0.329229,MAINSTREAM,0.360763,0.134685

In [19]:
feature_list = ['WEEK_END_DATE', 'FEATURE', 'DISPLAY', 'TPR_ONLY', 'STORE_NUM', 'UPC', 'UNITS', 'PRICE', 'BASE_PRICE', 'STORE_ID', 'MSA_CODE', 'SALES_AREA_SIZE_NUM', 'AVG_WEEKLY_BASKETS']

In [20]:
merged_data[feature_list]

,WEEK_END_DATE,FEATURE,DISPLAY,TPR_ONLY,STORE_NUM,UPC,UNITS,PRICE,BASE_PRICE,STORE_ID,MSA_CODE,SALES_AREA_SIZE_NUM,AVG_WEEKLY_BASKETS
0,2009-01-14,0,0,1,-1.610890,-0.442202,-0.220760,-1.277606,-1.245766,-1.610890,-0.645367,-1.887698,-1.350373
1,2009-01-14,0,0,0,-1.610890,-0.442202,0.013087,-1.277606,-1.356078,-1.610890,-0.645367,-1.887698,-1.350373
2,2009-01-14,0,0,0,-1.610890,-0.442202,-0.187353,-1.284020,-1.362207,-1.610890,-0.645367,-1.887698,-1.350373
3,2009-01-14,0,0,1,-1.610890,-0.442201,-0.521420,0.075563,0.543752,-1.610890,-0.645367,-1.887698,-1.350373
4,2009-01-14,0,0,0,-1.610890,-0.442201,-0.554826,-0.565749,-0.675817,-1.610890,-0.645367,-1.887698,-1.350373
...,...,...,...,...,...,...,...,...,...,...,...,...,...
524945,2012-01-04,0,0,0,1.627287,1.005835,-0.621640,1.018293,0.837919,1.627287,-0.329229,0.360763,0.134685
524946,2012-01-04,0,0,0,1.627287,1.005835,-0.488013,1.018293,0.837919,1.627287,-0.329229,0.360763,0.134685
524947,2012-01-04,0,0,0,1.627287,3.755346,0.413967,-0.046286,-0.179410,1.627287,-0.329229,0.360763,0.134685
524948,2012-01-04,0,0,0,1.627287,3.755346,0.347153,-0.046286,-0.179410,1.627287,-0.329229,0.360763,0.134685
524949,2012-01-04,0,0,1,1.627287,3.755346,0.013087,-0.745317,-0.461320,1.627287,-0.329229,0.360763,0.134685

In [21]:
merged_data

,WEEK_END_DATE,STORE_NUM,UPC,UNITS,VISITS,HHS,SPEND,PRICE,BASE_PRICE,FEATURE,...,SUB_CATEGORY,PRODUCT_SIZE,STORE_ID,STORE_NAME,ADDRESS_CITY_NAME,ADDRESS_STATE_PROV_CODE,MSA_CODE,SEG_VALUE_NAME,SALES_AREA_SIZE_NUM,AVG_WEEKLY_BASKETS
0,2009-01-14,-1.610890,-0.442202,-0.220760,13,13,18.07,-1.277606,-1.245766,0,...,PRETZELS,15 OZ,-1.610890,15TH & MADISON,COVINGTON,KY,-0.645367,VALUE,-1.887698,-1.350373
1,2009-01-14,-1.610890,-0.442202,0.013087,18,18,27.80,-1.277606,-1.356078,0,...,PRETZELS,15 OZ,-1.610890,15TH & MADISON,COVINGTON,KY,-0.645367,VALUE,-1.887698,-1.350373
2,2009-01-14,-1.610890,-0.442202,-0.187353,14,14,19.32,-1.284020,-1.362207,0,...,PRETZELS,15 OZ,-1.610890,15TH & MADISON,COVINGTON,KY,-0.645367,VALUE,-1.887698,-1.350373
3,2009-01-14,-1.610890,-0.442201,-0.521420,3,3,14.00,0.075563,0.543752,0,...,MOUTHWASHES (ANTISEPTIC),1.5 LT,-1.610890,15TH & MADISON,COVINGTON,KY,-0.645367,VALUE,-1.887698,-1.350373
4,2009-01-14,-1.610890,-0.442201,-0.554826,3,3,7.50,-0.565749,-0.675817,0,...,MOUTHWASHES (ANTISEPTIC),500 ML,-1.610890,15TH & MADISON,COVINGTON,KY,-0.645367,VALUE,-1.887698,-1.350373
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
524945,2012-01-04,1.627287,1.005835,-0.621640,1,1,4.97,1.018293,0.837919,0,...,MOUTHWASHES (ANTISEPTIC),1 LT,1.627287,CARROLLTON,CARROLLTON,TX,-0.329229,MAINSTREAM,0.360763,0.134685
524946,2012-01-04,1.627287,1.005835,-0.488013,5,5,24.85,1.018293,0.837919,0,...,MOUTHWASHES (ANTISEPTIC),1 LT,1.627287,CARROLLTON,CARROLLTON,TX,-0.329229,MAINSTREAM,0.360763,0.134685
524947,2012-01-04,1.627287,3.755346,0.413967,29,23,105.92,-0.046286,-0.179410,0,...,ADULT CEREAL,18 OZ,1.627287,CARROLLTON,CARROLLTON,TX,-0.329229,MAINSTREAM,0.360763,0.134685
524948,2012-01-04,1.627287,3.755346,0.347153,26,23,99.30,-0.046286,-0.179410,0,...,ADULT CEREAL,18 OZ,1.627287,CARROLLTON,CARROLLTON,TX,-0.329229,MAINSTREAM,0.360763,0.134685
524949,2012-01-04,1.627287,3.755346,0.013087,20,20,44.40,-0.745317,-0.461320,0,...,KIDS CEREAL,11 OZ,1.627287,CARROLLTON,CARROLLTON,TX,-0.329229,MAINSTREAM,0.360763,0.134685

In [22]:
merged_data.to_csv('data/processed/merged_data_norm_1017.csv')

In [2]:
merged_data = pd.read_csv('data/processed/merged_data_norm_1017.csv')

In [3]:
merged_data[:10]

,Unnamed: 0,WEEK_END_DATE,STORE_NUM,UPC,UNITS,VISITS,HHS,SPEND,PRICE,BASE_PRICE,...,SUB_CATEGORY,PRODUCT_SIZE,STORE_ID,STORE_NAME,ADDRESS_CITY_NAME,ADDRESS_STATE_PROV_CODE,MSA_CODE,SEG_VALUE_NAME,SALES_AREA_SIZE_NUM,AVG_WEEKLY_BASKETS
0,0,2009-01-14,-1.61089,-0.442202,-0.220760,13,13,18.07,-1.277606,-1.245766,...,PRETZELS,15 OZ,-1.61089,15TH & MADISON,COVINGTON,KY,-0.645367,VALUE,-1.887698,-1.350373
1,1,2009-01-14,-1.61089,-0.442202,0.013087,18,18,27.80,-1.277606,-1.356078,...,PRETZELS,15 OZ,-1.61089,15TH & MADISON,COVINGTON,KY,-0.645367,VALUE,-1.887698,-1.350373
2,2,2009-01-14,-1.61089,-0.442202,-0.187353,14,14,19.32,-1.284020,-1.362207,...,PRETZELS,15 OZ,-1.61089,15TH & MADISON,COVINGTON,KY,-0.645367,VALUE,-1.887698,-1.350373
3,3,2009-01-14,-1.61089,-0.442201,-0.521420,3,3,14.00,0.075563,0.543752,...,MOUTHWASHES (ANTISEPTIC),1.5 LT,-1.61089,15TH & MADISON,COVINGTON,KY,-0.645367,VALUE,-1.887698,-1.350373
4,4,2009-01-14,-1.61089,-0.442201,-0.554826,3,3,7.50,-0.565749,-0.675817,...,MOUTHWASHES (ANTISEPTIC),500 ML,-1.61089,15TH & MADISON,COVINGTON,KY,-0.645367,VALUE,-1.887698,-1.350373
5,5,2009-01-14,-1.61089,-0.442201,-0.588233,2,2,5.18,-0.508031,-0.620660,...,MOUTHWASHES (ANTISEPTIC),500 ML,-1.61089,15TH & MADISON,COVINGTON,KY,-0.645367,VALUE,-1.887698,-1.350373
6,6,2009-01-14,-1.61089,-0.442198,-0.187353,13,13,26.32,-0.963363,-1.055783,...,ALL FAMILY CEREAL,12.25 OZ,-1.61089,15TH & MADISON,COVINGTON,KY,-0.645367,VALUE,-1.887698,-1.350373
7,7,2009-01-14,-1.61089,-0.442198,0.313747,26,25,54.52,-0.963363,-1.055783,...,ADULT CEREAL,20 OZ,-1.61089,15TH & MADISON,COVINGTON,KY,-0.645367,VALUE,-1.887698,-1.350373
8,8,2009-01-14,-1.61089,-0.442198,0.514187,27,25,69.30,-0.899232,-0.994498,...,ALL FAMILY CEREAL,18 OZ,-1.61089,15TH & MADISON,COVINGTON,KY,-0.645367,VALUE,-1.887698,-1.350373
9,9,2009-01-14,-1.61089,-0.442198,1.015287,40,40,168.00,-0.014221,0.206685,...,PIZZA/PREMIUM,32.7 OZ,-1.61089,15TH & MADISON,COVINGTON,KY,-0.645367,VALUE,-1.887698,-1.350373

In [4]:
len(merged_data)

524950

In [5]:
merged_data.dropna(axis=0, how='any')

,Unnamed: 0,WEEK_END_DATE,STORE_NUM,UPC,UNITS,VISITS,HHS,SPEND,PRICE,BASE_PRICE,...,SUB_CATEGORY,PRODUCT_SIZE,STORE_ID,STORE_NAME,ADDRESS_CITY_NAME,ADDRESS_STATE_PROV_CODE,MSA_CODE,SEG_VALUE_NAME,SALES_AREA_SIZE_NUM,AVG_WEEKLY_BASKETS
0,0,2009-01-14,-1.610890,-0.442202,-0.220760,13,13,18.07,-1.277606,-1.245766,...,PRETZELS,15 OZ,-1.610890,15TH & MADISON,COVINGTON,KY,-0.645367,VALUE,-1.887698,-1.350373
1,1,2009-01-14,-1.610890,-0.442202,0.013087,18,18,27.80,-1.277606,-1.356078,...,PRETZELS,15 OZ,-1.610890,15TH & MADISON,COVINGTON,KY,-0.645367,VALUE,-1.887698,-1.350373
2,2,2009-01-14,-1.610890,-0.442202,-0.187353,14,14,19.32,-1.284020,-1.362207,...,PRETZELS,15 OZ,-1.610890,15TH & MADISON,COVINGTON,KY,-0.645367,VALUE,-1.887698,-1.350373
3,3,2009-01-14,-1.610890,-0.442201,-0.521420,3,3,14.00,0.075563,0.543752,...,MOUTHWASHES (ANTISEPTIC),1.5 LT,-1.610890,15TH & MADISON,COVINGTON,KY,-0.645367,VALUE,-1.887698,-1.350373
4,4,2009-01-14,-1.610890,-0.442201,-0.554826,3,3,7.50,-0.565749,-0.675817,...,MOUTHWASHES (ANTISEPTIC),500 ML,-1.610890,15TH & MADISON,COVINGTON,KY,-0.645367,VALUE,-1.887698,-1.350373
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
524945,524945,2012-01-04,1.627287,1.005835,-0.621640,1,1,4.97,1.018293,0.837919,...,MOUTHWASHES (ANTISEPTIC),1 LT,1.627287,CARROLLTON,CARROLLTON,TX,-0.329229,MAINSTREAM,0.360763,0.134685
524946,524946,2012-01-04,1.627287,1.005835,-0.488013,5,5,24.85,1.018293,0.837919,...,MOUTHWASHES (ANTISEPTIC),1 LT,1.627287,CARROLLTON,CARROLLTON,TX,-0.329229,MAINSTREAM,0.360763,0.134685
524947,524947,2012-01-04,1.627287,3.755346,0.413967,29,23,105.92,-0.046286,-0.179410,...,ADULT CEREAL,18 OZ,1.627287,CARROLLTON,CARROLLTON,TX,-0.329229,MAINSTREAM,0.360763,0.134685
524948,524948,2012-01-04,1.627287,3.755346,0.347153,26,23,99.30,-0.046286,-0.179410,...,ADULT CEREAL,18 OZ,1.627287,CARROLLTON,CARROLLTON,TX,-0.329229,MAINSTREAM,0.360763,0.134685
524949,524949,2012-01-04,1.627287,3.755346,0.013087,20,20,44.40,-0.745317,-0.461320,...,KIDS CEREAL,11 OZ,1.627287,CARROLLTON,CARROLLTON,TX,-0.329229,MAINSTREAM,0.360763,0.134685

In [6]:
len(merged_data)

524950

In [7]:
merged_data = merged_data.dropna(axis=0, how='any')

In [8]:
len(merged_data)

524742

In [9]:
merged_data = pd.read_csv('data/processed/merged_data_norm_3.csv')

In [10]:
merged_data[:20]

,Unnamed: 0,WEEK_END_DATE,STORE_NUM,UPC,UNITS,VISITS,HHS,SPEND,PRICE,BASE_PRICE,...,SUB_CATEGORY,PRODUCT_SIZE,STORE_ID,STORE_NAME,ADDRESS_CITY_NAME,ADDRESS_STATE_PROV_CODE,MSA_CODE,SEG_VALUE_NAME,SALES_AREA_SIZE_NUM,AVG_WEEKLY_BASKETS
0,0,2009-01-14,367,1111009477,-0.220760,13,13,18.07,-1.277606,-1.245766,...,PRETZELS,15 OZ,367,15TH & MADISON,COVINGTON,KY,17140,VALUE,24721,12706.532051
1,1,2009-01-14,367,1111009497,0.013087,18,18,27.80,-1.277606,-1.356078,...,PRETZELS,15 OZ,367,15TH & MADISON,COVINGTON,KY,17140,VALUE,24721,12706.532051
2,2,2009-01-14,367,1111009507,-0.187353,14,14,19.32,-1.284020,-1.362207,...,PRETZELS,15 OZ,367,15TH & MADISON,COVINGTON,KY,17140,VALUE,24721,12706.532051
3,3,2009-01-14,367,1111035398,-0.521420,3,3,14.00,0.075563,0.543752,...,MOUTHWASHES (ANTISEPTIC),1.5 LT,367,15TH & MADISON,COVINGTON,KY,17140,VALUE,24721,12706.532051
4,4,2009-01-14,367,1111038078,-0.554826,3,3,7.50,-0.565749,-0.675817,...,MOUTHWASHES (ANTISEPTIC),500 ML,367,15TH & MADISON,COVINGTON,KY,17140,VALUE,24721,12706.532051
5,5,2009-01-14,367,1111038080,-0.588233,2,2,5.18,-0.508031,-0.620660,...,MOUTHWASHES (ANTISEPTIC),500 ML,367,15TH & MADISON,COVINGTON,KY,17140,VALUE,24721,12706.532051
6,6,2009-01-14,367,1111085319,-0.187353,13,13,26.32,-0.963363,-1.055783,...,ALL FAMILY CEREAL,12.25 OZ,367,15TH & MADISON,COVINGTON,KY,17140,VALUE,24721,12706.532051
7,7,2009-01-14,367,1111085345,0.313747,26,25,54.52,-0.963363,-1.055783,...,ADULT CEREAL,20 OZ,367,15TH & MADISON,COVINGTON,KY,17140,VALUE,24721,12706.532051
8,8,2009-01-14,367,1111085350,0.514187,27,25,69.30,-0.899232,-0.994498,...,ALL FAMILY CEREAL,18 OZ,367,15TH & MADISON,COVINGTON,KY,17140,VALUE,24721,12706.532051
9,9,2009-01-14,367,1111087395,1.015287,40,40,168.00,-0.014221,0.206685,...,PIZZA/PREMIUM,32.7 OZ,367,15TH & MADISON,COVINGTON,KY,17140,VALUE,24721,12706.532051
10,10,2009-01-14,367,1111087396,1.382760,43,42,203.13,-0.033460,0.243456,...,PIZZA/PREMIUM,30.5 OZ,367,15TH & MADISON,COVINGTON,KY,17140,VALUE,24721,12706.532051
11,11,2009-01-14,367,1111087398,1.750233,52,49,238.32,-0.046286,0.243456,...,PIZZA/PREMIUM,29.6 OZ,367,15TH & MADISON,COVINGTON,KY,17140,VALUE,24721,12706.532051
12,12,2009-01-14,367,1600027527,-0.254166,10,10,38.28,-0.123244,-0.252951,...,ALL FAMILY CEREAL,12.25 OZ,367,15TH & MADISON,COVINGTON,KY,17140,VALUE,24721,12706.532051
13,13,2009-01-14,367,1600027528,0.380560,26,19,142.29,0.774594,0.605036,...,ALL FAMILY CEREAL,18 OZ,367,15TH & MADISON,COVINGTON,KY,17140,VALUE,24721,12706.532051
14,14,2009-01-14,367,1600027564,1.215726,48,42,152.32,-0.424661,-0.326493,...,ALL FAMILY CEREAL,12 OZ,367,15TH & MADISON,COVINGTON,KY,17140,VALUE,24721,12706.532051
15,15,2009-01-14,367,2840004768,-0.387793,6,6,23.12,-0.315638,-0.436806,...,PRETZELS,16 OZ,367,15TH & MADISON,COVINGTON,KY,17140,VALUE,24721,12706.532051
16,16,2009-01-14,367,3000006340,-0.020320,17,17,38.76,-0.860753,-0.528733,...,ALL FAMILY CEREAL,13 OZ,367,15TH & MADISON,COVINGTON,KY,17140,VALUE,24721,12706.532051
17,17,2009-01-14,367,3000006560,2.251333,76,72,174.00,-0.886406,-0.620660,...,KIDS CEREAL,13 OZ,367,15TH & MADISON,COVINGTON,KY,17140,VALUE,24721,12706.532051
18,18,2009-01-14,367,3000006610,0.948473,41,41,96.00,-0.886406,-0.620660,...,KIDS CEREAL,14 OZ,367,15TH & MADISON,COVINGTON,KY,17140,VALUE,24721,12706.532051
19,19,2009-01-14,367,3700019521,-0.588233,2,2,5.00,-0.565749,-0.069097,...,MOUTHWASH/RINSES AND SPRAYS,4.2 OZ,367,15TH & MADISON,COVINGTON,KY,17140,VALUE,24721,12706.532051

In [11]:
len(merged_data)

524950

In [12]:
merged_data = merged_data.dropna(axis=0, how='any')

In [13]:
merged_data[:10]

,Unnamed: 0,WEEK_END_DATE,STORE_NUM,UPC,UNITS,VISITS,HHS,SPEND,PRICE,BASE_PRICE,...,SUB_CATEGORY,PRODUCT_SIZE,STORE_ID,STORE_NAME,ADDRESS_CITY_NAME,ADDRESS_STATE_PROV_CODE,MSA_CODE,SEG_VALUE_NAME,SALES_AREA_SIZE_NUM,AVG_WEEKLY_BASKETS
0,0,2009-01-14,367,1111009477,-0.220760,13,13,18.07,-1.277606,-1.245766,...,PRETZELS,15 OZ,367,15TH & MADISON,COVINGTON,KY,17140,VALUE,24721,12706.532051
1,1,2009-01-14,367,1111009497,0.013087,18,18,27.80,-1.277606,-1.356078,...,PRETZELS,15 OZ,367,15TH & MADISON,COVINGTON,KY,17140,VALUE,24721,12706.532051
2,2,2009-01-14,367,1111009507,-0.187353,14,14,19.32,-1.284020,-1.362207,...,PRETZELS,15 OZ,367,15TH & MADISON,COVINGTON,KY,17140,VALUE,24721,12706.532051
3,3,2009-01-14,367,1111035398,-0.521420,3,3,14.00,0.075563,0.543752,...,MOUTHWASHES (ANTISEPTIC),1.5 LT,367,15TH & MADISON,COVINGTON,KY,17140,VALUE,24721,12706.532051
4,4,2009-01-14,367,1111038078,-0.554826,3,3,7.50,-0.565749,-0.675817,...,MOUTHWASHES (ANTISEPTIC),500 ML,367,15TH & MADISON,COVINGTON,KY,17140,VALUE,24721,12706.532051
5,5,2009-01-14,367,1111038080,-0.588233,2,2,5.18,-0.508031,-0.620660,...,MOUTHWASHES (ANTISEPTIC),500 ML,367,15TH & MADISON,COVINGTON,KY,17140,VALUE,24721,12706.532051
6,6,2009-01-14,367,1111085319,-0.187353,13,13,26.32,-0.963363,-1.055783,...,ALL FAMILY CEREAL,12.25 OZ,367,15TH & MADISON,COVINGTON,KY,17140,VALUE,24721,12706.532051
7,7,2009-01-14,367,1111085345,0.313747,26,25,54.52,-0.963363,-1.055783,...,ADULT CEREAL,20 OZ,367,15TH & MADISON,COVINGTON,KY,17140,VALUE,24721,12706.532051
8,8,2009-01-14,367,1111085350,0.514187,27,25,69.30,-0.899232,-0.994498,...,ALL FAMILY CEREAL,18 OZ,367,15TH & MADISON,COVINGTON,KY,17140,VALUE,24721,12706.532051
9,9,2009-01-14,367,1111087395,1.015287,40,40,168.00,-0.014221,0.206685,...,PIZZA/PREMIUM,32.7 OZ,367,15TH & MADISON,COVINGTON,KY,17140,VALUE,24721,12706.532051

In [14]:
len(merged_data)

524742

In [15]:
merged_data.to_csv('data/processed/merged_data_norm_1022.csv')